export { OFFENSE_FORMATIONS } from './offense';
export { DEFENSE_FORMATIONS, COVERAGES } from './defense';
export { DEMO_PLAYS } from './demoPlays';
export { PACKERS_2019_PLAYS, PACKERS_2019_PLAYS_REVISION, PACKERS_2019_PLAY_ID_PREFIX, PACKERS_2019_ROUTES, routeByName } from './packers2019Plays';
export { PACKERS_2019_FORMATIONS, PACKERS_2019_ID_PREFIX, PACKERS_2019_REVISION, PACKERS_2019_TAG } from './packers2019';
