/**
 * Import the Eagles 2026 All-22 chart + per-player JSON into the checked-in seeds.
 *
 *   npm run import:snaps                                   re-run from import-data/
 *   npm run import:snaps -- --xlsx a.xlsx --json b.json    other files (copied into import-data/ first)
 *
 * Every import-data/W<week>_*_playforge.json is read, so a new game is one more file.
 *   npm run import:snaps -- --mirror                       merge only exact Rt/Lt mirror pictures
 *   npm run import:snaps -- --split                        keep every Rt and Lt picture as its own formation
 * By default it is one card per call: a look charted Lt attaches, mirrored, to the Rt card of the same
 * name whose picture is closest. Hand-drawn snaps keep their own card.
 *
 * Same engine as the Formations > Import page (src/importers/snapChart), run with the seed timestamp
 * and deterministic ids, so a later import of the same files in the browser merges into these rows
 * instead of duplicating them. Same input, same bytes out.
 */
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SEED_TIME } from '../src/model/seedRules';
import { applyDrawnAlignments, buildImportPlan, mergeFormationsJson, parseChartXlsx, parseFormationsJson, type DrawnAlignments } from '../src/importers/snapChart';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'import-data');
const XLSX = path.join(DATA, 'eagles-all22-chart.xlsx');
/** Every game's per-player alignment file: import-data/W<week>_<teams>_playforge.json. */
const jsonFiles = () => readdirSync(DATA).filter((f) => /^W[0-9]+_.*_playforge[.]json$/.test(f)).sort();
/** Weeks charted frame by frame from the downloaded All-22 (scripts/film): that file beats the workbook's formation columns. */
const FILM_WINS_WEEKS = [1, 2];
const OUT = path.join(ROOT, 'src/seeds/data/eagles2026.json');
const REPORT = path.join(DATA, 'import-report.json');

const args = process.argv.slice(2);
const flag = (name: string) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const merge = args.includes('--split') ? 'split' : args.includes('--mirror') ? 'mirror' : 'call';
const mirror = merge !== 'split';
const mergeByCall = merge === 'call';
for (const opt of ['--xlsx', '--json'] as const) {
  const src = flag(opt);
  const target = opt === '--xlsx' ? XLSX : path.join(DATA, path.basename(src ?? ''));
  if (src) {
    mkdirSync(DATA, { recursive: true });
    copyFileSync(path.resolve(src), target);
    console.log(`${path.relative(ROOT, target)} refreshed from ${path.resolve(src)}`);
  }
}

const chart = parseChartXlsx(new Uint8Array(readFileSync(XLSX)));
const files = jsonFiles();
const DRAWN = path.join(DATA, 'drawn-alignments.json');
const drawn = existsSync(DRAWN) ? (JSON.parse(readFileSync(DRAWN, 'utf8')) as DrawnAlignments) : undefined;
const merged = applyDrawnAlignments(mergeFormationsJson(files.map((f) => readFileSync(path.join(DATA, f), 'utf8'))), drawn);
const json = parseFormationsJson(merged);
const team = json.game.team ?? 'PHI';
const season = json.game.season ?? 2026;
const plan = buildImportPlan({ chart, json }, { team, season, mirror, mergeByCall, now: SEED_TIME, builtin: true, naming: 'system', filmWinsWeeks: FILM_WINS_WEEKS, source: `${team} ${season} All-22 chart (${path.basename(XLSX)}, ${files.join(', ')})` });

const formations = plan.formations.map((p) => p.formation);
const snaps = plan.snaps;
const revision = createHash('sha1').update(JSON.stringify({ formations, snaps })).digest('hex').slice(0, 12);
const out = {
  _generated: 'Written by scripts/import-snaps.ts from import-data/. Edit the inputs and run `npm run import:snaps`; do not edit this file.',
  pack: 'eagles-2026',
  team,
  season,
  mirror,
  revision,
  formations,
  snaps,
};
mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(out, null, 1) + '\n');
writeFileSync(
  REPORT,
  JSON.stringify(
    {
      summary: plan.summary,
      formations: plan.formations.map((p) => ({ id: p.formation.id, name: p.formation.name, count: p.count, exact: p.exact, template: p.template, weeks: p.weeks, hashes: p.hashes, source: p.source, snapIds: p.snapIds, tags: p.formation.tags })),
      skipped: plan.skipped,
      warnings: plan.warnings,
    },
    null,
    2,
  ) + '\n',
);

const s = plan.summary;
console.log(`${s.snaps} snaps (${Object.entries(s.weeks).map(([w, n]) => `${w} ${n}`).join(', ')}; ${s.exact} exact, ${s.template} template) -> ${s.formations} formations -> ${path.relative(ROOT, OUT)}  revision ${revision}${merge === 'call' ? ' (one card per call)' : merge === 'mirror' ? ' (exact mirrors merged)' : ' (Rt and Lt apart)'}`);
console.log(`${plan.skipped.length} row(s) skipped, ${plan.warnings.length} warning(s) -> ${path.relative(ROOT, REPORT)}`);
console.log('\nTop 10 by usage:');
for (const p of plan.formations.slice(0, 10)) console.log(`  ${String(p.count).padStart(3)}  ${p.formation.name.padEnd(22)} ${p.source.padEnd(8)} W${p.weeks.join('+W')}`);
